### ISSUE TITLE
Indirect Jump In TAC

### ISSUE THREAD

**Issue by XiaowenHu96** [nevillegrech/gigahorse-toolchain#20]
Is there an indirect jump semantic in the TAC format produced by Gigahorse?

The syntax of a jump operation is `JUMP $var`. Although it seems like the `$var` can be a runtime computed result, from what I observe so far, `$var` is always a constant in the TAC format. (Same for `JUMPI`)

I have this concern because in some cases, a transaction can fail if the code is trying to jump to a destination that is not marked by a `JUMPDEST`. 
For example, this [contract](https://contract-library.com/contracts/Ethereum/29FEE0C5CFD04361152B92FB3EF1E36F36B78B43) with some particular input can trigger an ErrInvalidJump exception in go-ethereum, but from the TAC output, it is pretty obvious that such error can never occur because jumps are all static and they all jump to legal destinations. 

So I want to ask, does Gigahorse concern about indirect jump when dissembling the source code?

**Comment by XiaowenHu96** [comment]
To see those txns that trigger bad jumps: https://etherscan.io/address/0x29FEE0C5CFD04361152B92FB3EF1E36F36B78B43

**Comment by sifislag** [comment]
Hi,
Gigahorse deals with this issue by transforming those jumps away early on.
The jumps are identified here as you describe them:
https://github.com/nevillegrech/gigahorse-toolchain/blob/eeb77a41c9a6b218ae4eaf894fa9639ae73d3ce0/logic/local.dl#L281-L289

Their transformation can be found here:
https://github.com/nevillegrech/gigahorse-toolchain/blob/eeb77a41c9a6b218ae4eaf894fa9639ae73d3ce0/logic/local.dl#L687-L721
Essentially what the transformation does is, for each "invalid" jump, it creates a new block that has a `THROW` statement in our IR and makes the jump target that block instead.

In your case I think the invalid jump is statement `0x582` in our decompilation output (with `--disable_inline`).
Make sure you are using the latest version of gigahorse as there was a recent fix regarding this pattern.

**Comment by XiaowenHu96** [comment]
Hi,

Thanks for the quick reply. Yes, you are right, after sync with the latest branch, I'm able to find the `THROW` in the TAC output. 
I overlooked the bytecode and I was wrong saying the jump was caused by an indirect one --- the static jump at `0x33e` is the culprit.

**Comment by sifislag** [comment]
Furthermore, to answer the first part of your question, gigahorse reasons about direct/immediate and indirect/non-immediate jumps in the following way: a direct jump is a jump with a target that can be resolved inside a basic block, while an indirect one has a target that is pushed to the stack by a previous basic block. The former are identified at the local (intra-block) analysis level while the latter require a context-sensitive global control-flow graph to be built in order to resolve their targets.

However in both cases targets are limited to the constant values present in the original bytecode (and values that can be produced using them).

We haven't seen jumps that rely on external input in compiler-produced code. Thus, if such a thing appears, right now we wouldn't support it.
