### ISSUE TITLE
address

### ISSUE THREAD

**Issue by taka250** [nevillegrech/gigahorse-toolchain#96]
<img width="304" alt="image" src="https://github.com/nevillegrech/gigahorse-toolchain/assets/98207906/40af3723-aed7-48cb-afdb-593eda2ac79f">
Observe the following two blocks, why the display jumps to oxbc, but 0xbcB0x59 is written on the next block, what is the meaning?

**Comment by sifislag** [comment]
You can ignore the values of targets of jump statements and only use facts on `LocalBlockEdges` and `FallThroughEdges`. We leave it like that because the Block IDs in cases of transformations (like what you  observed, caused by inlining) are not hex values.  By the way you can use the appropriate channel in the [dedaub discord](https://discord.gg/F5X4HugTbc) for more direct questions.
